### ISSUE TITLE
Utiliser la page releases au lieu d'ajouter un .zip dans le code source

### ISSUE THREAD

**Issue by Albirew** [cedced19/free-mobile-desktop#1]
Est-il possible d'enlever le fichier zip du code source et de le mettre dans la partie releases ( https://github.com/cedced19/free-mobile-desktop/releases )?

Cela permet de différencier quand le code est plus à jour que le binaire par exemple, ainsi que de rajouter un numéro de version pour un suivi plus efficace.

Pour le readme, un lien qui pointe toujours vers la dernière release existera sous cette forme: https://github.com/cedced19/free-mobile-desktop/releases/latest

**Comment by cedced19** [comment]
Oui après réfléction, je pense le faire.
Je préfère garder le zip car quelques fois je ne veux pas publier de nouvelle version pour un petit ajustement du css...
Je le fait déjà avec mes modules npm.
Je pense le faire, si cela me convient niveau rapidité/simplicité.

**Comment by Albirew** [comment]
sur univers freebox via un article récent ( http://www.universfreebox.com/article/30905/ )

**Comment by cedced19** [comment]
Ok
