### ISSUE TITLE
Support Linux :D

### ISSUE THREAD

**Issue by LifeIsStrange** [cedced19/free-mobile-desktop#2]
Tout d'abord merci pour ton merveilleux travail c'est juste génial ! Et le tout en open source :) juste merci. 
S'il te plaît pourrai tu supporter Linux ? Je suis désolé je ne sais pas encore coder donc je ne pourrai pas t'aider :m

**Comment by cedced19** [comment]
J'utilise `nw.js`, un système qui permet d'utiliser les mêmes langages que pour les page web donc cela  peut être compiler sous linux.
Il y a d’ailleurs la [ligne qui permet de compiler](https://github.com/cedced19/free-mobile-desktop/blob/master/gulpfile.js#L102) pour linux je ne l'avais pas encore fait car je ne saivais pas si ça marche.

Tu peux maintenant la [télécharger](https://github.com/cedced19/free-mobile-desktop/releases/latest).

**Comment by LifeIsStrange** [comment]
Super, merci beaucoup !
